import type { Metadata } from "next";
import "@repo/ui/globals.css";
import { ThemeProvider } from "@repo/ui/components/theme-provider";
import { Header } from "@repo/ui/components/header";
import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Header className="h-16 flex items-center"></Header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
